"""Payment instructions (guidance only, no auto-payment)."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from config import ESIC_EMPLOYER_CODE, OUTPUT_DIR, PF_ESTABLISHMENT_CODE, PT_REGISTRATION_NO
from utils.date_utils import month_name, month_short_name, next_month_due_date


def _money(v: float) -> str:
    return f"₹{float(v):,.2f}"


def _output_dir(month: int, year: int, output_dir: Path | None = None) -> Path:
    base = output_dir or (OUTPUT_DIR / f"{year}_{month:02d}")
    base.mkdir(parents=True, exist_ok=True)
    return base


def build_payment_summary(employee_wages: Iterable[dict]) -> Dict[str, float]:
    """Build summary values for payment guidance."""
    rows = list(employee_wages)
    return {
        "pf_total": round(sum(float(r.get("pf_employee", 0) or 0) + float(r.get("pf_employer", 0) or 0) for r in rows), 2),
        "pf_employee_share": round(sum(float(r.get("pf_employee", 0) or 0) for r in rows), 2),
        "pf_employer_share": round(sum(float(r.get("pf_employer", 0) or 0) for r in rows), 2),
        "esic_total": round(sum(float(r.get("esic_employee", 0) or 0) + float(r.get("esic_employer", 0) or 0) for r in rows), 2),
        "esic_employee_share": round(sum(float(r.get("esic_employee", 0) or 0) for r in rows), 2),
        "esic_employer_share": round(sum(float(r.get("esic_employer", 0) or 0) for r in rows), 2),
        "pt_total": round(sum(float(r.get("pt", 0) or 0) for r in rows), 2),
        "net_payable": round(sum(float(r.get("net_payable", 0) or 0) for r in rows), 2),
        "employee_count": len(rows),
    }


def generate_payment_instructions(
    summary_data: Dict[str, float],
    month: int,
    year: int,
    output_dir: Path | None = None,
    company_config: dict | None = None,
) -> Path:
    """Generate payment instruction PDF only (no payment execution)."""
    pf_code = (company_config or {}).get("pf_establishment_code", PF_ESTABLISHMENT_CODE)
    esic_code = (company_config or {}).get("esic_employer_code", ESIC_EMPLOYER_CODE)
    pt_code = (company_config or {}).get("pt_registration_no", PT_REGISTRATION_NO)

    out_file = _output_dir(month, year, output_dir) / f"Payment_Instructions_{month_short_name(month)}_{year}.pdf"
    doc = SimpleDocTemplate(str(out_file), pagesize=A4, leftMargin=14 * mm, rightMargin=14 * mm)
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(f"Payment Instructions - {month_name(month)} {year}", styles["Title"]))
    story.append(Spacer(1, 8))
    story.append(Paragraph("<b>Important:</b> This system does not auto-pay challans. It only provides guided steps.", styles["Normal"]))
    story.append(Spacer(1, 10))

    pf_due = next_month_due_date(15, month, year)
    esic_due = next_month_due_date(15, month, year)
    pt_due = next_month_due_date(21, month, year)

    story.append(Paragraph("<b>1) PF Payment Instructions</b>", styles["Heading3"]))
    pf_lines = [
        "STEP 1: Login to Unified Portal (https://unifiedportal-mem.epfindia.gov.in)",
        "STEP 2: Go to Payments > Challan History > Generate Challan",
        "STEP 3: Upload ECR file generated by this system",
        f"STEP 4: Verify challan amount: {_money(summary_data.get('pf_total', 0))}",
        "STEP 5: Make payment via Net Banking/Challan",
        "STEP 6: Save payment receipt/TRRN number",
        f"Due Date: {pf_due.isoformat()} | Establishment Code: {pf_code}",
        f"Employee Share: {_money(summary_data.get('pf_employee_share', 0))} | Employer Share: {_money(summary_data.get('pf_employer_share', 0))}",
        "Late Penalty: 12% per annum on delayed amount",
    ]
    for line in pf_lines:
        story.append(Paragraph(line, styles["Normal"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>2) ESIC Payment Instructions</b>", styles["Heading3"]))
    esic_lines = [
        "STEP 1: Login to ESIC Portal (https://portal.esic.in)",
        "STEP 2: Go to Monthly Contribution > Online Challan",
        "STEP 3: Enter contribution period and amount",
        "STEP 4: Verify details and complete payment",
        "STEP 5: Save challan PDF and transaction number",
        f"Due Date: {esic_due.isoformat()} | Employer Code: {esic_code}",
        f"Employee Contribution: {_money(summary_data.get('esic_employee_share', 0))}",
        f"Employer Contribution: {_money(summary_data.get('esic_employer_share', 0))}",
        f"Total ESIC: {_money(summary_data.get('esic_total', 0))}",
        "Late Penalty: 12% per annum + damages",
    ]
    for line in esic_lines:
        story.append(Paragraph(line, styles["Normal"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>3) Professional Tax Payment Instructions</b>", styles["Heading3"]))
    pt_lines = [
        "STEP 1: Login to Maharashtra State Tax Portal",
        "STEP 2: Go to Professional Tax > Monthly Return",
        "STEP 3: File return, generate challan, and make payment",
        "STEP 4: Save acknowledgment copy",
        f"Due Date: {pt_due.isoformat()} | Registration No: {pt_code or 'N/A'}",
        f"Total PT Deducted: {_money(summary_data.get('pt_total', 0))}",
    ]
    for line in pt_lines:
        story.append(Paragraph(line, styles["Normal"]))
    story.append(Spacer(1, 8))

    story.append(Paragraph("<b>4) Bank Salary Payment Instructions</b>", styles["Heading3"]))
    bank_lines = [
        f"STEP 1: Download Bank_Payment_{month_short_name(month)}_{year}.xlsx",
        f"STEP 2: Download NACH_Upload_{month_short_name(month)}_{year}.csv (if your bank supports NACH/ACH CSV).",
        "STEP 3: Open your bank bulk upload portal (NEFT/RTGS/NACH)",
        "STEP 4: Upload NEFT_Upload sheet or NACH CSV as per bank requirement",
        f"STEP 5: Verify total amount: {_money(summary_data.get('net_payable', 0))}",
        "STEP 6: Authorize and complete payment",
        "STEP 7: Save transaction reference",
        f"Total Employees: {int(summary_data.get('employee_count', 0))}",
    ]
    for line in bank_lines:
        story.append(Paragraph(line, styles["Normal"]))

    doc.build(story)
    return out_file

